### ISSUE TITLE
streamtape not working still, on 5.1.18?

### ISSUE THREAD

**Issue by flapbird1** [jsergio123/script.module.resolveurl#411]
https://github.com/jsergio123/script.module.resolveurl/issues/409#issuecomment-751901998

Hi all,
streamtape not working still, on 5.1.18?
Can anyone confirm this
Many thanks in advance

**Comment by Gujal00** [comment]
yes it is broken in 5.1.18 and has been fixed here in git as per https://github.com/jsergio123/script.module.resolveurl/commit/a44de70b033acb94b66903f5d7687fd18713af51
WIll work in the next release when it happens

**Comment by flapbird1** [comment]
Many thanks @Gujal00 for the speedy response.
Overwrite patch  https://github.com/jsergio123/script.module.resolveurl/commit/a44de70b033acb94b66903f5d7687fd18713af51 and still fails (reset cache too)
Checked with UWC addon and websites:
XXXstreams (eu)
XXXstreams (org)

Keep up the great work
